upstream api {
    server backend:8000;
}

server {
    listen 8004;

    location /api/ {
        proxy_pass http://api;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/day {
        proxy_pass http://api/day;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}